version: '1'
services:
  notes_app:
    container_name: notes_app
    image: x0r5/notes_app
    restart: always
    build: .
    ports:
      - '3000:80'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'